name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libmagic1 tesseract-ocr

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint (placeholder)
        run: echo "Lint ok"

      - name: Run tests
        run: pytest -q

